# Load the data
original_datapath: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/rawdata/user_behavior_dataset.csv"

# File naming
mapping_name: "categorical_mapping.json"
intermediate_df_name: "transformed_df.csv"
x_train_name: "X_train.csv"
y_train_name: "y_train.csv"
x_test_name: "X_test.csv"
y_test_name: "y_test.csv"
x_train_normalized_name: "X_train_normalize.csv"
x_test_normalized_name: "X_test_normalized.csv"
x_train_standardized_name: "X_train_standardized.csv"
x_test_standardized_name: "X_test_standardized.csv"
best_parameters_name: "Best_parameters_model_"

# Transformations
categorical_columns_to_transform:
  - "DeviceModel"
  - "OperatingSystem"
  - "Gender"
columns_to_drop:
  - "UserID"
mapping_file_path: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/intermediate_data"
target_column: "UserBehaviorClass"
normalize_df: true
standardized_df: false
apply_feature_selection: false
feature_selection:
  - "AppUsageTime_min_day"
  - "ScreenOnTime_hours_day"
  - "BatteryDrain_mAh_day"
  - "NumberOfAppsInstalled"
  - "DataUsage_MB_day"

# Model selection and hyperparameter tuning
ML_type: "SVM"
number_iterations: 32
cross_validation: 3
feature_engineering_dict:
  C:
    - 1e-6
    - 10
  gamma:
    - scale
    - auto
  degree:
    - 1
    - 3
  kernel:
    - linear
    - poly
    - rbf
tuned_parameters_path: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/train_data"
feature_mode: "GridSearch"

# Saving Data File Paths
transformed_intermediate_df_path: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/intermediate_data"
transformed_train_df_path_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/train_data"
transformed_test_df_path_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/test_data"
transformed_train_df_path_y: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/train_data"
transformed_test_df_path_y: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/test_data"
transformed_normalized_df_path_train_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/train_data"
transformed_normalized_df_path_test_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/test_data"
transformed_standardized_df_path_train_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/train_data"
transformed_standardized_df_path_test_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/EDA_train_phase/data/processed_data/test_data"

