defaults:
  - Eda_config: Eda_config
  - train_config: train_config
  - transformation_config: transformation_config

dynamic_settings:
  ##GENERAL SETTINGS:
  experiment_name: "Tree_Classifier_GridSearchCV"
  ##SETTINGS FOR TRANSFORMATION AND TRAINING
  # load the original data
  original_datapath: "EDA_train_phase/data/rawdata/user_behavior_dataset.csv"

  # Transformations
  categorical_columns_to_transform:
    - "DeviceModel"
    - "OperatingSystem"
    - "Gender"
  columns_to_drop:
    - "UserID"
  target_column: "UserBehaviorClass"
  normalize_df: false # To normalize the dataframe (TransformationPipeline Setting)
  standardize_df: false # to standardize the dataframe (TransformationPipeline Setting)
  apply_feature_selection: true
  feature_selection:
    - "AppUsageTime_min_day"
    - "ScreenOnTime_hours_day"
    - "BatteryDrain_mAh_day"
    - "NumberOfAppsInstalled"
    - "DataUsage_MB_day"
  # Model selection and hyperparameter tuning
  ML_type: "Tree-Based" # Literal["SVM", "KNN", "PCA", "Gradient", "Tree-Based", "Naive"]
  number_iterations: 3
  cross_validation: 3
  feature_engineering_dict:
    criterion:
      - "gini"
      - "entropy"
      - "log_loss"
    splitter:
      - "best"
      - "random"
    max_depth:
      - 5
      - 10
      - 20
    min_samples_split:
      - 2
      - 5
      - 10
    min_samples_leaf:
      - 1
      - 2
      - 4
    max_features:
      - "sqrt"
      - "log2"
    class_weight:
      - "balanced"

  feature_mode: "GridSearch"
  #trainer settings
  model_path: "EDA_train_phase/src/models"
  normalized_df: true #to use the normalized dataframe for training and testing.
  standardized_df: false #to use the standardized dataframe for training and testing
  tuned_parameters: "EDA_train_phase/data/processed_data/train_data/Best_parameters_model__GridSearch_Tree-Based.json"
  average_mode: "micro"