data_path: "/home/tensorboard/PycharmProjects/mobile_usage_detection/data/kaggle_mobile_user_behaviour/user_behavior_dataset.csv"
columns: ["Device Model", "Operating System", "Gender"]
drop: "User ID"