
# Load the data


original_datapath: "/home/tensorboard/PycharmProjects/mobile_usage_detection/rawdata/user_behavior_dataset.csv"

# File naming
mapping_name: "categorical_mapping.json"
intermediate_df_name: "transformed_df.csv"
x_train_name: "X_train.csv"
y_train_name: "y_train.csv"
x_test_name: "X_test.csv"
y_test_name: "y_test.csv"
x_train_normalized: "X_train_normalize.csv"
x_test_normalized: "X_test_normalized.csv"
x_train_standardized: "X_train_standardized.csv"
x_test_standardized: "X_test_standardized.csv"
best_parameters_name: "Best_parameters_model_"
# Transformations
categorical_columns_to_transform:
  - "Device Model"
  - "Operating System"
  - "Gender"

columns_to_drop:
  - "User ID"

mapping_file_path: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/intermediate_data/mapping.json"
target_column: "UserBehaviorClass"

normalize_df: true

standardized_df: false

# Model selection and hyperparameter tuning
ML_type: "SVM"

feature_engineering_dict:
  test_1: 5.5
  degree: [1, 2, 3, 4, 5, 6, 7, 8]
  kernel: ['linear', 'poly', 'rbf']

tuned_parameters: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/train"

feature_mode: "BayesianOptim"

# Saving Data File Paths

transformed_intermediate_df_path: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/intermediate_data"

transformed_train_df_path_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/train"

transformed_test_df_path_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/test"

transformed_train_df_path_y: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/train"

transformed_test_df_path_y: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/test"

transformed_normalized_df_path_train_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/train"

transformed_normalized_df_path_test_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/test"

transformed_standardized_df_path_train_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/train"

transformed_standardized_df_path_test_x: "/home/tensorboard/PycharmProjects/mobile_usage_detection/src/test"

