defaults:
  - Eda_config: Eda_config
  - train_config: train_config
  - transformation_config: transformation_config

dynamic_settings:
  ##GENERAL SETTINGS:
  experiment_name: "Tree_Classifier_New_v4"
  registered_model_name: "sk-learn-Decision-Tree-Classifier-custom-params_V4"
  ##SETTINGS FOR TRANSFORMATION AND TRAINING
  # load the original DataTrain
  original_datapath: "TrainSrc/DataTrain/rawdata/user_behavior_dataset.csv"

  # Transformations
  categorical_columns_to_transform:
    - "DeviceModel"
    - "OperatingSystem"
    - "Gender"
  columns_to_drop:
    - "UserID"
  target_column: "UserBehaviorClass"
  normalize_df: false # To normalize the dataframe (TransformationPipeline Setting)
  standardize_df: false # to standardize the dataframe (TransformationPipeline Setting)
  apply_feature_selection: true
  feature_selection:
    - "AppUsageTime_min_day"
    - "ScreenOnTime_hours_day"
    - "BatteryDrain_mAh_day"
    - "NumberOfAppsInstalled"
    - "DataUsage_MB_day"
  # Model selection and hyperparameter tuning
  ML_type: "Tree-Based" # Literal["SVM", "KNN", "PCA", "Gradient", "Tree-Based", "Naive"]
  number_iterations: 3
  cross_validation: 3
  feature_engineering_dict:
    criterion:
      - "gini"
      - "entropy"
      - "log_loss"
    splitter:
      - "best"
      - "random"
    max_depth:
      - 5
      - 10
      - 20
    min_samples_split:
      - 2
      - 5
      - 10
    min_samples_leaf:
      - 1
      - 2
      - 4
    max_features:
      - "sqrt"
      - "log2"
    class_weight:
      - "balanced"

  feature_mode: "GridSearch"
  #trainer settings
  model_path: "TrainSrc/Phases/ModelsTrain"
  normalized_df: false #to use the normalized dataframe for training and testing.
  standardized_df: false #to use the standardized dataframe for training and testing
  tuned_parameters: "TrainSrc/MetricsTrain/Best_parameters_model__GridSearch_Tree-Based.json"
  using_custom_parameters: true
  custom_parameters:
    criterion: "gini"
    splitter: "random"
    max_depth: 4
    min_samples_split: 5
    min_samples_leaf: 2
    max_features: "log2"
    class_weight: "balanced"
  average_mode: "micro"