# VARIABLE NAMING

experiment_name: ${dynamic_settings.experiment_name}

# Train and test Paths

x_train: "EDA_train_phase/data/processed_data/train_data/X_train.csv"
x_test: "EDA_train_phase/data/processed_data/test_data/X_test.csv"
y_train: "EDA_train_phase/data/processed_data/train_data/y_train.csv"
y_test: "EDA_train_phase/data/processed_data/test_data/y_test.csv"

#Standardized and Normalized Paths

#normalized_x_train: "EDA_train_phase/data/processed_data/train_data/X_train_normalize.csv"
#standardized_x_train: None
#normalized_x_test: "EDA_train_phase/data/processed_data/test_data/X_test_normalized.csv"
#standardized_x_test: None

# Bolean parameters

normalized_df: ${dynamic_settings.normalized_df}
standardized_df: ${dynamic_settings.standardized_df}

# model path

model_path: "EDA_train_phase/models"

# tuned parameters and metrics
using_custom_parameters: ${dynamic_settings.using_custom_parameters}
custom_parameters: ${dynamic_settings.custom_parameters}
tuned_parameters: ${dynamic_settings.tuned_parameters}
average_mode: ${dynamic_settings.average_mode}
metrics: "EDA_train_phase/metrics"


